# Generated by Django 5.2.12 on 2026-03-11 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('previous_login', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_user_role',
                'managed': False,
            },
        ),
    ]
